[project]
name = "sl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dacite>=1.9.2",
    "datasets>=4.1.1",
    "ipykernel>=7.1.0",
    "mlstm-kernels>=2.0.2",
    "ninja>=1.13.0",
    "omegaconf>=2.3.0",
    "packaging>=25.0",
    "peft>=0.18.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-xdist>=3.8.0",
    "renumics-spotlight>=1.7.1",
    "tensorboard>=2.20.0",
    "tokenizers>=0.22.1",
    "torch>=2.8.0",
    "torch-tb-profiler>=0.4.3",
    "torcheval>=0.0.7",
    "torchinfo>=1.8.0",
    "torchmetrics>=1.8.2",
    "torchvision>=0.23.0",
    "torchviz>=0.0.3",
    "tqdm>=4.67.1",
    "xlstm>=2.0.5",
]

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[tool.uv.extra-build-dependencies]
flash-attn = ["torch"]
